import { Activity, AlertTriangle, CheckCircle2, Database, HardDrive, KeyRound, LoaderCircle, Server } from "lucide-react";
import { healthEndpoint } from "../lib/admin-utils";
import { useAdminAuth } from "../lib/auth";
import { useAsync } from "../lib/use-async";

export function SystemPage() {
  const { api } = useAdminAuth();
  const apiBaseUrl = import.meta.env.VITE_API_URL ?? "/api/v1";
  const health = useAsync(async () => { const response = await fetch(healthEndpoint(apiBaseUrl)); if (!response.ok) throw new Error("API 健康检查失败"); return response.json() as Promise<{ status: string; time: string; objectStorage?: { provider: string; status: string } }>; }, [api, apiBaseUrl]);
  const healthOk = health.data?.status === "ok";
  const objectStore = health.data?.objectStorage;
  return <div className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">OPERATIONS / SYSTEM</p><h1>系统状态</h1><p>单机部署的运行边界、服务健康与关键配置。</p></div></header><div className="system-grid"><article className={health.error || (health.data && !healthOk) ? "system-card--error" : ""}><Server /><div><p>API 服务</p><h2>{healthOk ? "运行正常" : health.loading ? "检查中" : "异常"}</h2><small>{health.data ? new Date(health.data.time).toLocaleString("zh-CN") : health.error || "正在连接服务"}</small></div>{health.loading ? <LoaderCircle className="system-check spin" /> : healthOk ? <CheckCircle2 className="system-check" /> : <AlertTriangle className="system-check" />}</article><article><Database /><div><p>主数据存储</p><h2>SQLite WAL</h2><small>8 个连接 · busy timeout 5s</small></div><CheckCircle2 className="system-check" /></article><article><HardDrive /><div><p>对象存储</p><h2>{objectStore?.provider === "minio" ? "MinIO 镜像" : "本地资源卷"}</h2><small>{objectStore?.provider === "minio" ? "covers / demos / playables 已完成启动对账" : "未启用对象存储镜像"}</small></div>{health.loading ? <LoaderCircle className="system-check spin" /> : objectStore?.status === "ready" || !objectStore ? <CheckCircle2 className="system-check" /> : <AlertTriangle className="system-check" />}</article><article><KeyRound /><div><p>身份认证</p><h2>JWT + bcrypt</h2><small>24 小时会话 · 管理 RBAC</small></div><CheckCircle2 className="system-check" /></article><article><HardDrive /><div><p>目标资源</p><h2>8 Core / 8 GB</h2><small>静态前端 + 单 API 进程</small></div><CheckCircle2 className="system-check" /></article></div><section className="admin-panel operations-note"><Activity /><div><p className="admin-kicker">DEPLOYMENT PROFILE</p><h2>模块化单体，为单机部署而生</h2><p>用户端和管理端编译为静态文件；Go API 使用一个进程，SQLite 使用 WAL 模式。生产环境由 Caddy 负责 TLS、静态文件和 API 反向代理，MinIO 负责管理资源的对象存储镜像。写负载或多节点需求增长后，可沿数据层边界迁移到 PostgreSQL。</p><dl><div><dt>API 内存预算</dt><dd>512 MB</dd></div><div><dt>静态服务</dt><dd>128 MB</dd></div><div><dt>SQLite + OS Cache</dt><dd>≤ 2 GB</dd></div><div><dt>系统余量</dt><dd>≥ 4 GB</dd></div></dl></div></section></div>;
}
